version: "3.8"

services:
  # Backend API
  node:
    container_name: node
    build: ./server/
    command: npm start
    working_dir: /app/server/
    env_file: .env
    environment:
      NODE_ENV: development
      POSTGRES_URI: $POSTGRES_URI
      REDIS_URI: $REDIS_URI
    ports:
      - "8080:8080"
    volumes:
      - ./server/:/app/server/

  # Postgres
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
    build: ./server/postgres
    ports:
      - "5431:5432"

  #Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
