version: "3.0"

services:
  # React Client
  web:
    image: 163575307513.dkr.ecr.eu-west-2.amazonaws.com/smart-recognition-client:latest
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: smart-recognition
        awslogs-region: eu-west-2
        awslogs-stream-prefix: web

  # Node Server
  node:
    image: 163575307513.dkr.ecr.eu-west-2.amazonaws.com/smart-recognition-server:latest
    command: npm start
    env_file: .env
    environment:
      NODE_ENV: production
      POSTGRES_URI: $POSTGRES_PRD_URI
      REDIS_URI: $REDIS_PRD_URI
    ports:
      - "8080:8080"
    logging:
      driver: awslogs
      options:
        awslogs-group: smart-recognition
        awslogs-region: eu-west-2
        awslogs-stream-prefix: node

  # MongoDB
  postgres:
    image: 163575307513.dkr.ecr.eu-west-2.amazonaws.com/smart-recognition-postgres
    env_file: .env
    ports:
      - "5432:5432"
    logging:
      driver: awslogs
      options:
        awslogs-group: smart-recognition
        awslogs-region: eu-west-2
        awslogs-stream-prefix: postgres

  #Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    logging:
      driver: awslogs
      options:
        awslogs-group: smart-recognition
        awslogs-region: eu-west-2
        awslogs-stream-prefix: redis
